name: Secrets and Parameters
run-name: Retrieve AWS Secret and Variable by ${{ github.actor }}

on:
  # push:
  #   branches:
  #     - main
  #     - master
  #     - feature/*
  #     - develop
  workflow_dispatch:

jobs:
  Retrieve-Secrets-Parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id prod/azmi1/secrets --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_hobby=$(echo "$secret_object" | jq -r '. | fromjson | .azmi_hobby')
          secret_value_food=$(echo "$secret_object" | jq -r '. | fromjson | .azmi_food')
          secret_value_music=$(echo "$secret_object" | jq -r '. | fromjson | .azmi_music')

          echo "Secret value Hobby is: $secret_value_hobby"
          echo "Secret value Food is: $secret_value_food"
          echo "Secret value Music is: $secret_value_music"

      - name: Get Parameter Object
        run: |
          phone_value=$(aws ssm get-parameter --name azmi_phone --query Parameter.Value --output text)
          echo "Azmi's phone model is: $phone_value" 

          watch_value=$(aws ssm get-parameter --name azmi_watch --query Parameter.Value --output text)
          echo "Azmi's watch is: $watch_value"
