name: Terraform Apply
run-name: Running Terraform Apply by ${{ github.actor }}

on:
  push:
    branches:
      - "*"
    paths:
      - "terraform/*"

jobs:
  Terraform-Apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform workspace list
        run: terraform workspace list

      - name: Terraform workspace new environment and select
        env:
          WORKSPACE_NAME: ${{ github.base_ref == 'prod' && 'prod' || (github.base_ref == 'uat' && 'uat' || 'dev') }}
        run: |
          terraform workspace select $WORKSPACE_NAME || terraform workspace new $WORKSPACE_NAME
          terraform workspace list

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve -var-file="${{ github.base_ref == 'prod' && 'prod.tfvars' || (github.base_ref == 'uat' && 'uat.tfvars' || 'dev.tfvars') }}"

      - name: Export terraform outputs
        id: tfout
        run: |
          terraform output

      # - name: Wait for 15min
      #   run: sleep 900

      # - name: Terraform Destroy
      #   run: terraform destroy -no-color -auto-approve
