name: Terraform Destroy
run-name: Running Terraform Destroy by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "type DESTROY to confirm"
        required: true

jobs:
  Terraform-Destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform workspace list
        run: terraform workspace list

      - name: Terraform workspace new environment and select
        env:
          TF_WORKSPACE: ${{ github.ref == 'refs/heads/prod' && 'prod' || github.ref == 'refs/heads/uat' && 'uat' || 'dev' }}
        run: |
          terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
          terraform workspace list

      - name: Terraform Destroy
        if: ${{ github.event.inputs.confirmation }} == "DESTROY"
        id: destroy
        run: terraform destroy -auto-approve -var-file="${{ github.ref == 'refs/heads/prod' && 'prod.tfvars' || github.ref == 'refs/heads/uat' && 'uat.tfvars' || 'dev.tfvars' }}"
        continue-on-error: true
